# Generated by Django 4.1.1 on 2022-11-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customauthusermodel',
            options={'verbose_name': 'Custom User Model'},
        ),
    ]
