# Generated by Django 4.1.1 on 2022-09-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customauthusermodel",
            name="username",
            field=models.EmailField(
                default=1, max_length=254, unique=True, verbose_name="email address"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customauthusermodel",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
