# Generated by Django 4.1.1 on 2022-09-15 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customauthusermodel_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customauthusermodel",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=16,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
